# Generated by Django 3.1.4 on 2021-03-03 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='জেলার নাম ইংরেজিতে')),
                ('bn_name', models.CharField(max_length=100, null=True, unique=True, verbose_name='জেলার নাম বাংলায়')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='জেলার কোড')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(max_length=120, null=True, unique=True, verbose_name='ওয়েবসাইটের ঠিকানা')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='ইউনিয়নের নাম ইংরেজিতে')),
                ('bn_name', models.CharField(max_length=100, null=True, unique=True, verbose_name='ইউনিয়নের নাম বাংলায়')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='ইউনিয়নের কোড')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(max_length=120, null=True, unique=True, verbose_name='ওয়েবসাইটের ঠিকানা')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='গ্রামের নাম ইংরেজিতে')),
                ('bn_name', models.CharField(max_length=100, null=True, unique=True, verbose_name='গ্রামের নাম বাংলায়')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='গ্রামের কোড')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(max_length=120, null=True, unique=True, verbose_name='ওয়েবসাইটের ঠিকানা')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('union', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoCodeBD_app.union', verbose_name='ইউনিয়ন')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='উপজেলার নাম ইংরেজিতে')),
                ('bn_name', models.CharField(max_length=100, null=True, unique=True, verbose_name='উপজেলার নাম বাংলায়')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='উপজেলার কোড')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(max_length=120, null=True, unique=True, verbose_name='ওয়েবসাইটের ঠিকানা')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoCodeBD_app.district', verbose_name='জেলা')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='union',
            name='upazila',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoCodeBD_app.upazila', verbose_name='উপজেলা'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='বিভাগের নাম ইংরেজিতে')),
                ('bn_name', models.CharField(max_length=100, null=True, unique=True, verbose_name='বিভাগের নাম বাংলায়')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='বিভাগের কোড')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(max_length=120, null=True, unique=True, verbose_name='ওয়েবসাইটের ঠিকানা')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoCodeBD_app.division', verbose_name='বিভাগ'),
        ),
    ]
