# Generated by Django 3.1.4 on 2021-03-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoCodeBD_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='bn_name',
            field=models.CharField(max_length=100, null=True, verbose_name='ইউনিয়নের নাম বাংলায়'),
        ),
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='ইউনিয়নের নাম ইংরেজিতে'),
        ),
        migrations.AlterField(
            model_name='upazila',
            name='bn_name',
            field=models.CharField(max_length=100, null=True, verbose_name='উপজেলার নাম বাংলায়'),
        ),
        migrations.AlterField(
            model_name='upazila',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='উপজেলার নাম ইংরেজিতে'),
        ),
        migrations.AlterField(
            model_name='village',
            name='bn_name',
            field=models.CharField(max_length=100, null=True, verbose_name='গ্রামের নাম বাংলায়'),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='গ্রামের নাম ইংরেজিতে'),
        ),
    ]
