# Generated by Django 3.1.4 on 2021-03-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoCodeBD_app', '0002_auto_20210304_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='url',
            field=models.CharField(max_length=120, null=True, verbose_name='ওয়েবসাইটের ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='village',
            name='url',
            field=models.CharField(max_length=120, null=True, verbose_name='ওয়েবসাইটের ঠিকানা'),
        ),
    ]
