# Generated by Django 3.1.4 on 2021-03-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoCodeBD_app', '0003_auto_20210304_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='url',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='ওয়েবসাইটের ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='upazila',
            name='url',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='ওয়েবসাইটের ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='village',
            name='url',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='ওয়েবসাইটের ঠিকানা'),
        ),
    ]
